"""empty message

Revision ID: 5cb8bb9812a3
Revises: 363be07a4870
Create Date: 2020-06-10 17:05:40.850516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb8bb9812a3'
down_revision = '363be07a4870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('artists', 'genres')
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
